# Generated by Django 4.1.4 on 2022-12-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_id_alter_student_name_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
