# Generated by Django 4.1.4 on 2022-12-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
