# Generated by Django 4.1.4 on 2022-12-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_grades_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstQuarter',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('g_math', models.FloatField()),
                ('g_natural_sciences', models.FloatField()),
                ('g_human_sciences', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
