# Generated by Django 4.1.4 on 2022-12-19 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_firstquarter_delete_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquarter',
            name='g_human_sciences',
            field=models.FloatField(verbose_name='Human Science'),
        ),
        migrations.AlterField(
            model_name='firstquarter',
            name='g_math',
            field=models.FloatField(verbose_name='Math'),
        ),
        migrations.AlterField(
            model_name='firstquarter',
            name='g_natural_sciences',
            field=models.FloatField(verbose_name='Natural Science'),
        ),
        migrations.CreateModel(
            name='SecondQuarter',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('g_math', models.FloatField(verbose_name='Math')),
                ('g_natural_sciences', models.FloatField(verbose_name='Natural Science')),
                ('g_human_sciences', models.FloatField(verbose_name='Human Sciences')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
