# Generated by Django 4.1.4 on 2022-12-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_firstquarter_g_human_sciences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdQuarter',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('g_math', models.FloatField(verbose_name='Math')),
                ('g_natural_sciences', models.FloatField(verbose_name='Natural Sciences')),
                ('g_human_sciences', models.FloatField(verbose_name='Human Sciences')),
                ('studend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
