# Generated by Django 4.1.4 on 2022-12-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_thirdquarter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdquarter',
            old_name='studend',
            new_name='student',
        ),
    ]
